model_list:
  - model_name: gpt-4
    litellm_params:
      model: github_copilot/gpt-4
      extra_headers:
        Editor-Version: "vscode/1.85.1"
        Copilot-Integration-Id: "vscode-chat"

  - model_name: gpt-5-mini
    litellm_params:
      model: github_copilot/gpt-5-mini
      extra_headers:
        Editor-Version: "vscode/1.85.1"
        Copilot-Integration-Id: "vscode-chat"
        reasoning_effort: "low"

  - model_name: haiku
    litellm_params:
      model: anthropic/claude-3-haiku

  - model_name: embedding-large
    litellm_params:
      model: openai/text-embedding-3-large

  - model_name: deepseek-r1
    litellm_params:
      model: deepseek/deepseek-r1